# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0004_introduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
