# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0005_delete_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('birthday', models.DateField(default=datetime.date(2015, 1, 1))),
            ],
        ),
    ]
