# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='birthday',
            field=models.CharField(max_length=20),
        ),
    ]
