# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(max_length=5),
        ),
    ]
