# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_auto_20171003_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
