# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0014_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='user.png', upload_to='user-img'),
        ),
    ]
