# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0016_userfollower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
