# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0018_auto_20171019_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.Posts', unique=True)),
            ],
        ),
    ]
