# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0019_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='grumblr.Posts', unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(),
        ),
    ]
