# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0020_auto_20171020_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='picture',
            field=models.ImageField(blank=True, default='user.png', upload_to='user-img'),
        ),
    ]
